pretrain_weights: https://bj.bcebos.com/paddle3d/models/centerpoint//centerpoint_pillars_016voxel_kitti/model.pdparams
slim_type: QAT

slim_config:
  quant_config: {
      'weight_quantize_type': 'channel_wise_abs_max',
      'activation_quantize_type': 'moving_average_abs_max',
      'weight_bits': 8,
      'activation_bits': 8,
      'dtype': 'int8',
      'window_size': 10000,
      'moving_rate': 0.9,
      'quantizable_layer_type': ['Conv2D', 'Linear']}

finetune_config:
  epochs: 1

  lr_scheduler:
    type: OneCycleWarmupDecayLr
    base_learning_rate: 0.0005
    lr_ratio_peak: 10
    lr_ratio_trough: 0.0001
    step_ratio_peak: 0.4
